### ISSUE TITLE
Can I just distill the image?

### ISSUE THREAD

**Issue by alexandsunny** [wkcn/TinyCLIP#1]
If I only distill the image side and not the text side, will the effect be better than distilling both sides?

**Comment by wkcn** [comment]
Hi @alexandsunny, thanks for your attention to our work!

In my experience, distilling both two branches is better than distilling a branch.

**Comment by alexandsunny** [comment]
> Hi @alexandsunny, thanks for your attention to our work!
> 
> In my experience, distilling both two branches is better than distilling a branch.

Thank you for your patient answer！！！
