### ISSUE TITLE
Does model weight convertible between HF model weight and Open_clip model weight?

### ISSUE THREAD

**Issue by hyeinhyun** [wkcn/TinyCLIP#4]
Hi I wonder model weight is convertible between HF model weight and Open_clip model weight.
HF model weight : https://huggingface.co/wkcn/TinyCLIP-ViT-40M-32-Text-19M-LAION400M
Open clip model : https://github.com/wkcn/TinyCLIP-model-zoo/releases/download/checkpoints/TinyCLIP-ViT-40M-32-Text-19M-LAION400M.pt

I found there are some difference between 2 models 
1) proj layer of visual model
I think there is the named "proj" layer that open_clip based model has but hf based model doesn't have. 

2) Archictecture of VisionTransformers is littlie different.
openclip : layernorm - attention - layernorm - mlp
hf : attention - layernorm - mlp - layernorm

Because of these differences, I think model weight is not convertible. Am I right?

**Comment by wkcn** [comment]
Hi @hyeinhyun , thanks for your attention to our work!

The architecture of TinyCLIP is the same as that of CLIP/open CLIP.

Regarding to your questions,
1. the `proj` layer in open_clip is corresponding to the `visual_projection` layer in HF (https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/modeling_clip.py#L1454).
2. The vision transformer in HF is also the architecture: layernorm - attention - layernorm - mlp
https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/modeling_clip.py#L558-L570

**Comment by wkcn** [comment]
You can refer to the script for model conversion:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/convert_clip_original_pytorch_to_hf.py

**Comment by hyeinhyun** [comment]
It works! thanks
