### ISSUE TITLE
Tiny CLIP performance not upto mark

### ISSUE THREAD

**Issue by adi070701** [wkcn/TinyCLIP#6]
Hi,
I was testing out the performance for the image branch of TinyCLIP-ViT-40M-32-Text-19M-LAION400M and comparing it to vanilla clip-vit-base-patch32. Although TinyCLIP has half the parameters as clip-vit-base-paths32 it is only giving a 10% improvement to inference speed. Is this expected?

**Comment by wkcn** [comment]
Hi @adi070701 , thanks for your attention to our work!

The reason may be that the batch size is relatively small, resulting in underutilization of the hardware.

You can try using ONNX Runtime or PyTorch JIT for model inference while increasing the batch size.
